# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jason/var/aatree/old

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jason/var/aatree/old

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jason/var/aatree/old/CMakeFiles /home/jason/var/aatree/old/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jason/var/aatree/old/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ip_location

# Build rule for target.
ip_location: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ip_location
.PHONY : ip_location

# fast build rule for target.
ip_location/fast:
	$(MAKE) -f CMakeFiles/ip_location.dir/build.make CMakeFiles/ip_location.dir/build
.PHONY : ip_location/fast

aatree.o: aatree.cpp.o
.PHONY : aatree.o

# target to build an object file
aatree.cpp.o:
	$(MAKE) -f CMakeFiles/ip_location.dir/build.make CMakeFiles/ip_location.dir/aatree.cpp.o
.PHONY : aatree.cpp.o

aatree.i: aatree.cpp.i
.PHONY : aatree.i

# target to preprocess a source file
aatree.cpp.i:
	$(MAKE) -f CMakeFiles/ip_location.dir/build.make CMakeFiles/ip_location.dir/aatree.cpp.i
.PHONY : aatree.cpp.i

aatree.s: aatree.cpp.s
.PHONY : aatree.s

# target to generate assembly for a file
aatree.cpp.s:
	$(MAKE) -f CMakeFiles/ip_location.dir/build.make CMakeFiles/ip_location.dir/aatree.cpp.s
.PHONY : aatree.cpp.s

ip_location.o: ip_location.cpp.o
.PHONY : ip_location.o

# target to build an object file
ip_location.cpp.o:
	$(MAKE) -f CMakeFiles/ip_location.dir/build.make CMakeFiles/ip_location.dir/ip_location.cpp.o
.PHONY : ip_location.cpp.o

ip_location.i: ip_location.cpp.i
.PHONY : ip_location.i

# target to preprocess a source file
ip_location.cpp.i:
	$(MAKE) -f CMakeFiles/ip_location.dir/build.make CMakeFiles/ip_location.dir/ip_location.cpp.i
.PHONY : ip_location.cpp.i

ip_location.s: ip_location.cpp.s
.PHONY : ip_location.s

# target to generate assembly for a file
ip_location.cpp.s:
	$(MAKE) -f CMakeFiles/ip_location.dir/build.make CMakeFiles/ip_location.dir/ip_location.cpp.s
.PHONY : ip_location.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... ip_location"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... aatree.o"
	@echo "... aatree.i"
	@echo "... aatree.s"
	@echo "... ip_location.o"
	@echo "... ip_location.i"
	@echo "... ip_location.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

